### ISSUE TITLE
No method named 'unwrap_or_default' for env::current_dir()

### ISSUE THREAD

**Issue by Afulton11** [ben01189998819991197253/contrail#1]
Error while running 'cargo test && cargo install' during compilation of contrail on my Macbook pro. I'll propose a file change, but it wouldn't have a fallback; It would just panic since it just replaces 'unwrap_or_default' with the normal 'unwrap'. The error message makes it seem like there is an easy fix that would allow for unwrap_or_default to be used, I'm just not too familiar with rust's error messages.

![](http://i.imgur.com/89trk5U.png)

Using 'unwrap' should be fine since we should always be in a valid directory; However, if the directory we are in was deleted while we were in it maybe we would get a panic with using unwrap.

**Comment by bepzi** [comment]
That error message is just saying that we're attempting to call a method, `unwrap_or_default()`, that hasn't been implemented for the type `PathBuf` (it needs the trait `Default`). Which if you think about it, makes sense -- `unwrap_or_default()` attempts to unwrap the `Result`, and will return a default value otherwise -- what's the default value of trying to find the current directory?

My only concern, like you said, is that contrail will simply panic if the current directory isn't found. That's currently the biggest issue with the code: reckless use of `unwrap()`. I'll do more research later on the proper way to handle that.
