### ISSUE TITLE
Path output by the directory module includes any symlinks followed

### ISSUE THREAD

**Issue by bepzi** [ben01189998819991197253/contrail#3]
On my machine, I have `~/.sync/documents` symlinked to `~/documents`. With other powerline implementations, I expect to just see `~/documents`, because I don't care about where the folder *actually* is. With contrail, I see the full path taken.

There should be a config option (perhaps called `show_followed_symlinks`) for the directory module that enables/disables the showing of any symlinks traversed. By default, it should be disabled.

**Comment by Afulton11** [comment]
I found a couple links that may help with this: 
[fn read_link](https://doc.rust-lang.org/std/fs/fn.read_link.html)
and
[Filesystem operations](http://rustbyexample.com/std_misc/fs.html)

[This](http://stackoverflow.com/questions/30511331/getting-the-absolute-path-from-a-pathbuf/38384901#38384901) last one I found on StackOverflow a bit later appears to be the right way to resolve symlinks with paths in rust. So we should retrieve the current directory and then canonicalize it.

**Comment by bepzi** [comment]
I'll have to do some more testing in a separate dummy crate. If you want to test this out yourself, make a symlink with:

```bash
# General syntax is `ln -s <target> <destination>` like the `cp` command
ln -s ~/path/to/far/away/thing/you/want ~/where/you/want/it
```

and then see if you can get Rust to only print out `~/where/you/want/it`

**Comment by Afulton11** [comment]
Ohh, I see, I was thinking of something entirely different. After doing a bit of research, I realized that this might be quite difficult to implement without drastically slowing down performance to the point where contrail is almost unusable because there are so many symbolic links on a computer. Not only that, but once we found all the symbolic links that linked to a specific path, how we would choose which symbolic link to show in the terminal? 

Followed symbolic links might be a bit easier, we could use this command: 
`find -L /dir/to/start -samefile destination`
but this still takes forever even when I only have 1 symlink from '~/' to 'my destination directory' and if there were multiple symlinks to the same destination, we wouldn't know which one to show.

I was about to say we should just add a config option that would hold an array of directories whose paths you wish would show up differently with their wanted paths....

but I came across the fact that the `pwd` command always echoes the symlinked path and not the actual path even when going deeper into the symlinked directory. I think we can use the `pwd` command instead of using `env::current_dir()` to get the current path when the `show_followed_symlink` option is true.

I'm not sure if this is true across all operating systems, but it works for osx/bash at least.

**Comment by Afulton11** [comment]
At first, I wrote a block of code to execute the 'pwd' and retrieve its output, but then decided to read the man page on `pwd`. I Found that the -L for argument only works if the shell updates the `PWD` environment variable and rust can access environment variables directly; so, I wrote this block of code:

```
 let cwd = if c.get_bool("modules.directory.show_followed_symlinks").unwrap_or_default() {
        // Since we should follow system links, find the current path using the 'pwd -L' command
        // The 'pwd -L' command only works if the shell updates the PWD environment variable.

        // Match the PWD envrionment variable
        match env::var("PWD") {
            Ok(var_pwd) => {
                // Create a new PathBuffer from the found Logical Working Directory
                PathBuf::from(var_pwd)
            },
            Err(_) => {
                // The 'pwd -L' must not be supported in this shell, return the absolute (physical) path instead.
                env::current_dir().unwrap()
            }
        }
    } else {
        // Return the current directory without following system links (absoloute path)
        env::current_dir().unwrap()
    };
```
I think this should work on most shells and has the desired output, I'll make a pull request.
